name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish NuGet
      env:
        working-directory: ./NukedBit.Core
      run: dotnet nuget push "bin/Release/NukedBit.Core.0.0.1.nupkg" --source "github"
